### ISSUE TITLE
add user positive/negative dict

### ISSUE THREAD

**Issue by YifengLuo** [ikegami-yukino/oseti#5]
hi, developer,

thanks for offering this amazing tool to deal with Japanese sentiment analysis. I know oseti is based on dict to calculate the sentiment. I am not sure it is possible to adding user positive/negative dict into the system dict? 

If it is possible, could u tell me how to add it. many thanks~

**Comment by ikegami-yukino** [comment]
@YifengLuo 
The latest version supports the user's dictionary.
Please try it!
